<table border="2px solid black">
    <tr>
        <th><?= __('Name'); ?></th>
        <th><?= __('Contact No'); ?></th>
        <th colspan="3"><?= __('Action'); ?></th>
    </tr>
    <?php
        $collectionData = $block->getAllData();
        $total = count($collectionData);
        for($i = $total; $i>=$total; $i--){
            echo $i;
        }
        foreach($collectionData as $collection):
    ?>
    <tr>
        <td><?= $collection->getEmail(); ?></td>
        <td><?= $collection->getLastName(); ?></td>
        <td>
             <a class="action primary" href="<?= $block->getUrl('crud/page/insert'); ?>">Add Record</a>
        </td>
        <td>
            <a href="<?= $block->getUrl('crud/page/edit').'id/'.$collection->getId(); ?>" class="action primary">Edit</a>
            
        </td>
        <td>
            <a href="<?= $block->getUrl('crud/page/delete').'?id='.$collection->getId(); ?>" class="action primary">Delete</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>